# Exploratory Data Analysis

### Imports/Reading Files

In [20]:
import pandas as pd
import numpy as np
from datetime import datetime

In [21]:
movies = pd.read_csv('../data/tmdb_5000_movies.csv')
credits = pd.read_csv('../data/tmdb_5000_credits.csv')

## Movies Dataset

In [22]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [23]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [24]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [25]:
movies.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

## Credits Dataset

In [26]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

In [27]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [28]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

In [29]:
credits.describe()

            movie_id
count    4803.000000
mean    57165.484281
std     88694.614033
min         5.000000
25%      9014.500000
50%     14629.000000
75%     58610.500000
max    459488.000000

### Additional Testing

In [30]:
movies = movies.merge(credits, left_on='id', right_on='movie_id', how='left')
movies.rename(columns={'vote_average': 'rating', 'title_x': 'title'}, inplace=True)
movies.drop('title_y', axis=1, inplace=True)
movies.drop('movie_id', axis=1, inplace=True)

In [31]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'rating',
       'vote_count', 'cast', 'crew'],
      dtype='object')

In [32]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,revenue,runtime,spoken_languages,status,tagline,title,rating,vote_count,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [33]:
avatar_film = movies[movies['title'] == 'Avatar']
avatar_genres = avatar_film['genres']
for genre in avatar_genres:
    print(genre)

[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]

In [34]:
# all unique genres
import json
unique_genres = set()
for genres in movies['genres']:
    for g in json.loads(genres):
        unique_genres.add(g['name'])
unique_genres

{'Action',
 'Adventure',
 'Animation',
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Family',
 'Fantasy',
 'Foreign',
 'History',
 'Horror',
 'Music',
 'Mystery',
 'Romance',
 'Science Fiction',
 'TV Movie',
 'Thriller',
 'War',
 'Western'}

In [35]:
# movies[movies['title'] == 'After Hours']
# movies[movies['title'] == 'Show Me']
# movies[movies['title'] == 'War']
movies[movies['title'] == 'After']

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,revenue,runtime,spoken_languages,status,tagline,title,rating,vote_count,cast,crew
4492,0,"[{""id"": 9648, ""name"": ""Mystery""}, {""id"": 53, ""...",NaN,118612,"[{""id"": 732, ""name"": ""coma""}, {""id"": 14541, ""n...",en,After,When two bus crash survivors awake to discover...,4.596157,"[{""name"": ""Seabourne Pictures"", ""id"": 25566}, ...",...,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,After,5.6,63,"[{""cast_id"": 1, ""character"": ""Freddy"", ""credit...","[{""credit_id"": ""553d13d09251413f5a007eec"", ""de..."

In [37]:
prod_companies = movies['production_companies'].unique()
print(prod_companies)

['[{"name": "Ingenious Film Partners", "id": 289}, {"name": "Twentieth Century Fox Film Corporation", "id": 306}, {"name": "Dune Entertainment", "id": 444}, {"name": "Lightstorm Entertainment", "id": 574}]'
 '[{"name": "Walt Disney Pictures", "id": 2}, {"name": "Jerry Bruckheimer Films", "id": 130}, {"name": "Second Mate Productions", "id": 19936}]'
 '[{"name": "Columbia Pictures", "id": 5}, {"name": "Danjaq", "id": 10761}, {"name": "B24", "id": 69434}]'
 ...
 '[{"name": "Asylum Films", "id": 10571}, {"name": "FM Entertainment", "id": 26598}, {"name": "Eagle Eye Films Inc.", "id": 40739}]'
 '[{"name": "Front Street Pictures", "id": 3958}, {"name": "Muse Entertainment Enterprises", "id": 6438}]'
 '[{"name": "rusty bear entertainment", "id": 87986}, {"name": "lucky crow films", "id": 87987}]']

In [49]:
production_companies = set()
for row in movies['production_companies']:
    try:
        companies = json.loads(row.replace("'", "\""))  # some rows may use single quotes
        for company in companies:
            name = company['name'].lower().strip()
            production_companies.add(name)
    except Exception:
        continue

In [70]:
"wb" in production_companies

False

In [71]:
print(sorted(production_companies))
# add synonyms "Fox", "WB", "Warner Bros"

['"dia" productions gmbh & co. kg', '1.85 films', '10 west studios', '100 bares', '1019 entertainment', '101st street films', '10th hole productions', '120 films', '120db films', '13 ghosts productions canada inc.', '1492 pictures', '1812 productions', '1818', '1821 pictures', '19 entertainment', '1984 private defense contractors', '2 entertain', '2 loop films', '2003 productions', '20th century fox home entertainment', '20th century fox russia', '21 laps entertainment', '21st century film production', '22 & indiana pictures', '26 films', '2929 productions', '2dux²', '2s films', '3 arts entertainment', '3 dogs and a pony', '3 in the box', '3 miles apart productions ltd.', '30 something productions', '31 juin films', '33 pictures', '33andout productions', '34th street films', '360 pictures', '369 productions', '3ality digital entertainment', '3d entertainment', '3dtk', '3foot7', '3l filmproduktion gmbh', '3mark entertainment', '3rd partner productions', '4 1/2 film', '40 acres & a mule filmworks', '4dh films', '4go west productions', '4m', '5150 action', '80 days productions', '87eleven', '8:38 productions', '98 mph productions', 'a b corp', 'a band apart', 'a bigger boat', 'a grand elephant', 'a happy place', 'a hot dog', 'a loopy production llc', 'a lucky old sun production', 'a may sky picture entertainment', 'a plus image', 'a space between', 'a&b producoes', 'a&e television networks', 'a-mark entertainment', 'a-team', 'a. film', 'a.j.o.z. films', 'a113', 'a24', 'aardman animations', 'abandon entertainment', 'abbolita productions', 'abc pictures', 'abe shuji', 'abraham productions', 'absinthe productions', 'absolute entertainment (ii)', 'abu dhabi film commission', 'abundant productions', 'academy films', 'acajou films', 'access films', 'access motion picture group', 'ace film company', 'achte babelsberg film', 'across the river productions', 'act iii', 'act iii communications', 'ad hominem enterprises', 'ada films', 'adam fields productions', 'adam productions', 'adam schroeder productions', 'addis wechsler pictures', 'adela pictures', 'adf acquisitions', 'adlabs films ltd.', 'adscott pictures', 'adventure pictures', 'ae two film productions', 'aegis film fund', 'affirm films', 'afg talons productions', 'afrodita audiovisual, a.i.e.', 'after dark films', 'after eden pictures', 'against the wild films', 'agencja produkcji filmowej', 'aggregate film', 'aggregate films', 'agi orsi productions', 'agresywna banda', 'ahimsa films', 'ai-film', 'airborne productions', 'aitysh film', 'aja / levasseur productions', 'akil production company', 'akira committee company ltd.', 'alabama production group', 'alameda films', 'alan greenspan productions', 'alan jay lerner productions', 'alan young pictures', 'albert s. ruddy productions', 'alberta film entertainment', 'alberto grimaldi productions', 'albino alligator productions', 'alcon entertainment', 'alcor films', 'aldamisa entertainment', 'aldrich group', 'alex entertainment inc.', 'alexandre films', 'alfama films', 'alfran productions', 'alfred j. hitchcock productions', 'algonquin productions limited', 'alibaba pictures group', 'alibella pictures', 'alive films', 'all girl productions', 'all knight productions', 'all lit up productions', 'all night productions', 'all pictures media', 'allagash films', 'allan zeman productions', 'allegiance theater', 'alliance atlantis communications', 'alliance communications', 'alliance entertainment', 'alliance films', 'allied artists', 'allied artists pictures', 'allied filmmakers', 'allied stars, ltd.', 'allied vision', 'allison shearmur productions', 'alloy entertainment', 'allure entertainment', 'almerica films', 'aloha pictures', 'alpha core', 'alphaville films', 'alphaville productions', 'also known as pictures', 'alta loma entertainment', 'altavista films', 'altitude entertainment', 'alvernia studios', 'amaro films', 'amasia entertainment', 'amaze film + television', 'amazon prime instant video', 'amazon studios', 'amberdale productions', 'ambience entertainment', 'ambient entertainment gmbh', 'amblin entertainment', 'ambush entertainment', 'amc pictures', 'amen ra films', 'amercent films', 'american empirical pictures', 'american entertainment investors', 'american entertainment partners ii l.p.', 'american entertainment partners l.p.', 'american film company', 'american film institute (afi)', 'american films', 'american filmworks', 'american girl brands', 'american international pictures (aip)', 'american playhouse theatrical films', 'american work', 'american zoetrope', 'amok productions', 'amusement park films', 'amy robinson productions', 'an olive branch productions', 'ana media', 'anagram pictures inc.', 'anarchos productions', 'anchor bay entertainment', 'anchor bay films', 'ancine', 'andalasia productions', 'andale pictures', 'andell entertainment', 'andrea sperling productions', 'andreevsky flag film company', 'andrew lauren productions (alp)', 'angel city pictures', 'angel eyes productions', 'angel films', 'angry films', 'anima estudios', 'animal kingdom', 'animal logic', 'animal planet', 'animated family films', 'animation picture company', 'animationwerks', 'animus films', 'anka film', 'ankor-film', 'annapurna pictures', 'annuit coeptis entertainment ii', 'annuit coeptis entertainment inc.', 'anomaly entertainment', 'anonymous content', 'anouchka films', 'antares produzione cinematografica', 'antena 3 films', 'antena 3 televisión', 'anthem productions', 'antidote films (i)', 'antietam filmworks', 'anton capital entertainment (ace)', 'antzworks', 'anvil films', 'apaches entertainment', 'apatow productions', 'aperture entertainment', 'apipoulaï', 'apjac international', 'apjac productions', 'apollomedia distribution', 'apollopromedia gmbh & co. 1. filmproduktion kg (i)', 'apostle productions', 'apotheosis media group', 'apparatus productions', 'appian way', 'applause pictures', 'applecross', 'applehead pictures', 'april films', 'apropos films', 'aquafilms', 'ar films', 'ar-tl', 'arachnid productions ltd.', 'aramid entertainment fund', 'arc productions', 'arcade pictures', 'arcadia motion pictures', 'archer gray', 'archer street productions', 'arco films s.l', 'ard', 'ard degeto film', 'ardustry entertainment', 'area japan', 'arena', 'argonaut pictures', 'argyle enterprises', 'ariane mararía films', 'ariescope pictures', 'arion communications ltd.', 'aristos films', 'arka media works', 'arlington road productions corporation', 'armada films', 'armory films', 'arnold kopelson productions', 'arrowstorm entertainment', 'arsénico producciones', 'art in motion', 'art linson productions', 'art pictures studio', 'artcam y fonds sud cinéma', 'arte', 'arte france', 'arte france cinéma', 'artemis films', 'artemple - hollywood', 'artfire films', 'artic productions llc', 'artina films', 'artisan entertainment', 'artist international', 'artist international management', 'artists independent network', 'artists production group (apg)', 'artists public domain', 'arts council of england', 'arturo gonzález producciones cinematográficas s.a.', 'artémis productions', 'asaf', 'asahi soft drinks company', 'ascendant pictures', 'ascension pictures', 'ascension productions', 'ascot elite entertainment group', 'ascot elite home entertainment', 'asghar farhadi productions', 'ashton productions', 'asia union film & entertainment ltd.', 'asig productions', 'asis productions', 'asmik ace entertainment', 'asqa film partnership', 'assassin films', 'associated general films', 'ast studios', 'astral bellevue pathé', 'astral films', 'astral media', 'asylum', 'asylum films', 'asymmetrical productions', 'atchity entertainment international (aei)', 'atlantic entertainment group', 'atlantic pictures', 'atlantic swiss productions', 'atlantic television', 'atlantis pictures', 'atlas 2 productions', 'atlas 3 productions', 'atlas entertainment', 'atman entertainment', 'atmosphere entertainment mm', 'ato pictures', 'atomic monster', 'atr films', 'attitude pinículas y films a.i.e.', 'audiovisual aval sgr', 'audley films', 'audley films llp', 'august entertainment', 'august heart entertainment', 'australian film finance corporation', 'australian film finance corporation (affc)', 'automatik entertainment', 'autonomous', 'av club, the', 'av pictures', 'avalanche productions', 'avco embassy pictures', 'avenging conscience', 'avenue pictures productions', 'aver media', 'aversano films', 'avery pix', 'avi arad productions', 'avikoo studios', 'avon production', 'axon films', 'azl productions kg', 'azoff entertainment', 'aztec musique', 'b media 2012', 'b.d.s. productions inc.', 'b.h. finance c.v.', 'b.sting entertainment', 'b24', 'babbo inc.', 'babcock & brown', 'babe ruthless productions', 'babelsberg film', 'babieka', 'baby cow productions', 'baby films', 'babylon', 'babylon films limited', 'bac films', 'back lot pictures', 'backup films', 'backup media', 'bad cop bad cop film productions', 'bad hat harry productions', 'bad robot', 'bagdasarian productions', 'bagman (2009)', 'bago pictures', 'bait productions', 'baldwin entertainment group', 'baleuko s.l.', 'ballpark productions partnership', 'balthazar productions', 'baltimore pictures', 'baltimore spring creek pictures', 'baltimore spring creek productions', 'bandai visual company', 'bandito brothers', 'bandoola productions', 'bangkok dangerous', 'banque populaire images 9', 'banques populaire image 7', 'banter', 'barbarian films', 'barclays mercantile industrial finance', 'barentsfilm', 'barmak film', 'barry mendel productions', 'barunson', 'barwood films', 'base 12 productions', 'bates entertainment', 'battlefield productions', 'battleplan productions', 'baumgarten management and productions (bmp)', 'baumgarten merims productions', 'baumgarten-prophet entertainment', 'bavaria film', 'bavaria studios', 'bay films', 'bayahibe films ltd.', 'bayerischer rundfunk (br)', 'bazelevs production', 'bazmark films', 'bb film productions', 'bbc', 'bbc earth', 'bbc earth md (wwd)', 'bbc films', 'bbc scotland', 'bbc storyville', 'bbc worldwide', 'bcdf pictures', 'be gentlemen limited partnership', 'be your own hollywood', 'beacon communications', 'beacon pictures', 'beagle pug films', 'beanca films', 'bearing fruit entertainment', 'bece canada productions', 'becker international', 'bedford falls company, the', 'bedford falls productions', 'bedlam pictures', 'bedlam productions', 'bee vine pictures', 'beech hill films', 'before the door pictures', 'behavioral problem productions ltd.', 'beijing gallop horse film & tv production', 'beijing happy pictures cultural communications co.', 'beijing heguchuan tv & film', 'beijing jinyinma movie & tv culture co.', 'beijing new picture film co. ltd.', 'beijing poly-bona film publishing company', 'beijing silver moon productions', 'bekmambetov projects ltd.', 'bel air entertainment', 'belhaven limited', 'believe entertainment', 'bell broadcast and new media fund', 'bella productions', 'belladonna productions', 'belle pictures', 'belstar productions', 'ben-ami/leeds productions', 'benaroya pictures', 'bend it films', 'benderspink', 'bentley filmgroup', 'bergsten music', 'berlanti productions', 'bernard gayle productions', 'bernd eichinger productions', 'berrick filmproduktion', 'bersin pictures', 'best picture show company, the', 'better wide', 'beverly detroit', 'beverly ridge pictures', 'bh tilt', 'bi-polar pictures', 'big arty productions', 'big beach films', 'big book media', 'big bug pictures', 'big easy pictures', 'big idea productions', 'big indie pictures', 'big kid pictures', 'big lou house productions', 'big primate pictures', 'big screen productions', 'big talk productions', 'big ticket productions', 'bill graham films', 'bill kenwright films', 'bill plympton studios', 'bill/phillips', 'billblock media', 'bim distribuzione', 'biograf jan svěrák', 'birchwood pictures', 'bird and a bear entertainment', 'birdsong pictures', 'biride productions', 'birka holding', 'birnbaum / barber productions', 'birnbaum/barber', 'biscayne pictures', 'bisgrove entertainment', 'bitart new media', 'bk', 'black & white productions', 'black and blu entertainment', 'black bear pictures', 'black diamond pictures', 'black entertainment television (bet)', 'black label media', 'blackfriars bridge films', 'blackmagic design films', 'blank of the dead productions', 'bleiberg entertainment', 'blind spot pictures oy', 'blind wink', 'blind wink productions', 'blinding edge pictures', 'blinkworks media', 'bliss media', 'blizzard entertainment', 'block / hanson', 'block 2 pictures', 'blood & chocolate productions ltd', 'blood & wine productions', 'bloodline productions', 'blossom films', 'blue askew', 'blue dot productions', 'blue flower productions', 'blue gardenia productions', 'blue guitar films', 'blue light', 'blue parrot productions', 'blue productions', 'blue sea productions', 'blue sky films', 'blue sky studios', 'blue star pictures', 'blue star productions', 'blue trail entertainment', 'blue train productions', 'blue tulip productions', 'blue wolf', 'blue yonder films', 'blue-tongue films', 'blueeyes productions', 'bluegrass films', 'blueprint pictures', 'bluewater pictures', 'blumhouse productions', 'blump international films', 'bms finance', 'bn films', 'bndes', 'bob industries', 'bob yari productions', 'bobby jones films llc', 'boies / schiller film group', 'bold films', 'boll kg', 'boll kino beteiligungs gmbh & co. kg', 'bollywood hollywood production', 'bomar ood', 'bona fide productions', 'bona international film group', 'bonnie timmermann productions', 'boo productions', 'bookshop productions', 'boram entertainment inc.', 'borderline films', 'born of war', 'boréales', 'bottom line entertainment', 'bottom of the ninth productions', 'bourne again', 'bow and arrow entertainment', 'boxing cat films', 'br group', 'brad grey pictures', 'brad krevoy & steve stabler production', 'brad zions films', 'brandywine productions', 'brass hat films', 'brat na pont productions', 'brave new films', 'braveworld productions', 'breaking ball films', 'breakup productions', 'brian barrett pictures', 'brian grazer/scott rudin productions', 'brick dust productions llc', 'bridget johnson films', 'bright cold day films', 'brightlight pictures', 'brightside entertainment', 'brillstein-grey entertainment', 'brink films', 'bristol automotive', 'bristol bay productions', 'british broadcasting corporation (bbc)', 'british broadcasting corporation (bbc) television', 'british columbia film', 'british film council', 'british film institute', 'british film institute (bfi)', 'british screen', 'british screen productions', 'britt allcroft productions', 'broad green pictures', 'broadway video', 'broken chair flickz', 'broken lizard industries', 'broken road productions', 'bron studios', 'brood syndicate', 'brooklyn films ii', 'brooks media', 'brooksfilms', 'brooksfilms ltd.', 'brookstreet pictures', 'brookwell-mcnamara entertainment', 'brothers dowdle productions', 'brownhouse productions', 'brownstone productions', 'bruin grip services', 'bsm studio', 'buckaroo entertainment', 'buena vista', 'buena vista home entertainment', 'bueprint pictures', 'buffalo gal pictures', 'bulletproof cupid', 'bullwinkle studios', 'bungalow 78 productions', 'bungalow productions', 'burg/koules productions', 'burke/samples/foster productions', 'burn later productions', 'burnside entertainment', 'burro productions', 'busboy productions', 'bushwick factory', 'business location sudtirol alto adige', 'buttercup films ltd.', 'butterfly productions', 'byronic pose productions', 'bystander films', 'bystorm films', 'bésame mucho pictures', 'bórd scannán na héireann', 'c & l', 'c&p productions', 'c-2 pictures', 'c.h.u.d. productions', 'c.r.g. international', 'c.r.r.a.v. nord pas de calais', 'cactus flower producciones', 'calder road film', 'caliber media company', 'calimari productions', 'callahan filmworks', 'calle cruzada', 'caltex films', 'cambridge productions', 'camellia productions', 'camelot pictures', 'camelot productions', 'camera stylo films', 'cameron mackintosh', 'camp / thompson pictures', 'campanile productions', 'campbell grobman films', 'camphor cinema', 'canada television and cable production fund license program (ctcpf)', 'canadian broadcasting corporation (cbc)', 'canadian film centre (cfc)', 'canadian film development corporation (cfdc)', 'canadian film or video production tax credit (cptc)', 'canadian television fund', 'canal plus', 'canal plus group', 'canal plus overseas', 'canal+', 'canal+ droits audiovisuels', 'canal+ españa', 'canal+ polska', 'canal+ television ab', 'canal+polska', 'caneo films', 'canlaws productions', 'cannell studios', 'cannon films', 'cannon group', 'cannon pictures', 'cantharus productions', 'capacity pictures', 'capcom', 'cape of good films', 'capella international', 'capitol films', 'cappa productions', 'capstone entertainment group', 'captivate entertainment', 'caravan pictures', 'cargo entertainment', 'carmel entertainment', 'carnaby international', 'carnival films', 'caro-mcleod', 'carol baum productions', 'carolco international n.v.', 'carolco pictures', 'carolina bank', 'carousel picture company', 'carousel picture company, the', 'carousel productions', 'carsey-werner company', 'carthago films s.a.r.l.', 'cartier productions', 'cartoon network', 'cartoon network studios', 'cartoon saloon', 'caruso / mendelsohn productions', 'case 39 productions', 'casey productions', 'casey silver productions', 'castel film romania', 'castelao producciones', 'castle rock entertainment', 'casual friday productions', 'catch 23 entertainment', 'catch productions', 'catchplay', 'catfish productions', 'catherine bailey ltd.', 'catmandu branded entertainment', 'cattleya', 'catwoman films', 'caviar films', 'cbs films', 'cdi', 'cecchi gori group tiger cinematografica', 'cecchi gori pictures', 'celador films', 'celador productions', 'celluloid dreams', 'cent productions inc.', 'centauri media', 'central cinema company film', 'central films', 'central motion pictures', 'central-europa film', 'centre national de la cinématographie', 'centre national de la cinématographie (cnc)', 'centre régional des ressources audiovisuelles (crrav)', 'centropolis entertainment', 'centropolis film productions', 'centrul national al cinematografiei (cnc)', 'centurion investment', 'chad troutwine films', 'chako film company', 'challenge film corporation', 'chambara pictures', 'channel four films', 'channel one russia', 'chaocorp', 'chapter 2', 'chapter one films', 'character matters', 'charenton productions', 'charenton productions limited', 'charles chaplin productions', 'charles k. feldman group', 'charlie guidance', 'chartoff productions', 'chartoff winkler productions', 'chartoff-winkler productions', 'chase productions', 'chateau productions', 'chatrone', 'cheap and dirty productions inc.', 'cheerland entertainment organization', 'cheetah vision', 'chengtian entertainment', 'cheongeoram', 'cheri productions', 'chernin entertainment', 'cherry alley productions', 'cherry on top', 'cherry road films llc', 'cheyenne enterprises', 'chi-fou-mi productions', 'chicago overcoat productions', 'chicago pacific entertainment', 'chickflick productions', 'chickie the cop production', 'chime films', 'china dream film culture industry', 'china film & tv capital', 'china film co-production corporation', 'china film co.', 'china film group corporation', 'china film group corporation (cfgc)', 'china movie channel', 'chockstone pictures', 'choke film', 'chris brinker productions', 'chris lee productions', 'christiano film group', 'christmas tree films', 'chromewood productions', 'chrysalis films', 'chrysler corporation', 'chuan production film studio', 'chubu-nippon broadcasting company (cbc)', 'chum television', 'chunqiu time culture co.', 'ciby 2000', 'ciclic - région centre', 'cimarron productions', 'cindy cowan entertainment', 'cine bazar', 'cine canibal', 'cine grande corporation', 'cine productions', 'cineblue internationale filmproduktionsgesellschaft', 'cineclick asi